---
image: docker:stable
services:
- docker:dind

stages:
- build
- push

before_script:
  - echo $AW_REGISTRY_PASSWORD | docker login -u "$AW_REGISTRY_USER" --password-stdin $AW_REGISTRY
  - echo $CI_DOCKER_REGISTRY_PASSWORD | docker login -u "$CI_DOCKER_REGISTRY_USER" --password-stdin $CI_DOCKER_REGISTRY
  - export AW_IMAGE_NAME=${AW_REGISTRY}/${AW_PROJECT_NAME}/${CI_PROJECT_NAME}
  - >
    if [ $CI_COMMIT_REF_NAME == "master" ]; then
      export TAG_VERSION=latest
    else
      export TAG_VERSION=${CI_COMMIT_REF_NAME}
    fi

build-image:
  stage: build
  script:
  - docker build --pull -t ${AW_IMAGE_NAME}:${TAG_VERSION} .
  - docker push ${AW_IMAGE_NAME}:${TAG_VERSION}

push-on-dockerhub:
  stage: push
  script:
  - docker tag ${AW_IMAGE_NAME}:${TAG_VERSION} ${CI_DOCKER_REGISTRY_IMAGE}:${TAG_VERSION}
  - docker push ${CI_DOCKER_REGISTRY_IMAGE}:${TAG_VERSION}
