apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-iaas
  labels:
    app.kubernetes.io/name: multi-iaas
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: multi-iaas
  template:
    metadata:
      labels:
        app.kubernetes.io/name: multi-iaas
    spec:
      volumes:
      - name: aws-volume
        secret:
          secretName: aws-key
      - name: gcp-volume
        secret:
          secretName: gcp-key
      imagePullSecrets:
        - name: access-token
      containers:
        - name: multi-iaas
          imagePullPolicy: Always
          image: hub.rnd.alterway.fr/overboard/5gbiller/multi-iaas-billing-exporter:test
          env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/key.json
          volumeMounts:
            - mountPath: /var/secrets/aws/
              name: aws-volume
            - mountPath: /var/secrets/google/
              name: gcp-volume
          ports:
          - containerPort: 9999
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: multi-iaas-svc
  labels:
    app.kubernetes.io/name: multi-iaas
spec:
  selector:
    app.kubernetes.io/name: multi-iaas
  type: ClusterIP
  ports:
  - name: multi-iaas
    port: 9999
    protocol: TCP
    targetPort: 9999
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: multi-iaas-svc-monitor
  labels:
    k8s-app: multi-iaas-svc-monitor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: multi-iaas
  endpoints:
  - interval: 60s
    targetPort: 9999
    path: '/metrics'
