apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-iaas-billing-exporter
  labels:
    app.kubernetes.io/name: multi-iaas-billing-exporter
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: multi-iaas-billing-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: multi-iaas-billing-exporter
    spec:
      volumes:
      - name: aws-volume
        secret:
          secretName: aws-key
      - name: gcp-volume
        secret:
          secretName: gcp-key
      imagePullSecrets:
        - name: access-token
      containers:
        - name: multi-iaas-billing-exporter
          imagePullPolicy: Always
          image: alterwayrnd/multi-iaas-billing-exporter:latest
          env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/key.json
          - name: GCP_PROJECTID
            value: ""
          - name: GCP_TABLE
            value: ""
          volumeMounts:
            - mountPath: /var/secrets/aws/
              name: aws-volume
            - mountPath: /var/secrets/google/
              name: gcp-volume
          ports:
          - containerPort: 9999
          resources: 
            requests:
              cpu: "500m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: multi-iaas-billing-exporter-svc
  labels:
    app.kubernetes.io/name: multi-iaas-billing-exporter
spec:
  selector:
    app.kubernetes.io/name: multi-iaas-billing-exporter
  type: ClusterIP
  ports:
  - name: multi-iaas-billing-exporter
    port: 9999
    protocol: TCP
    targetPort: 9999
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: multi-iaas-billing-exporter-svc-monitor
  labels:
    k8s-app: multi-iaas-billing-exporter-svc-monitor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: multi-iaas-billing-exporter
  endpoints:
  - interval: 3600s
    targetPort: 9999
    path: '/metrics'
